create role reader_role;
GRANT USAGE ON DATABASE HEALTHCARE_DB TO ROLE reader_role;
GRANT USAGE ON SCHEMA HEALTHCARE_DB.GOLD TO ROLE READER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE_DB.GOLD TO ROLE READER_ROLE;
GRANT role reader_role to user ANAND_JHA;


GRANT USAGE ON WAREHOUSE HEALTHCARE_WH TO ROLE reader_role;


GRANT USAGE ON SCHEMA HEALTHCARE_DB.raw TO ROLE READER_ROLE;
GRANT USAGE ON SCHEMA HEALTHCARE_DB.GOLD TO ROLE READER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE_DB.raw TO ROLE READER_ROLE;;

-- Grant access to the stage where the skill files are stored
GRANT USAGE ON STAGE HEALTHCARE_DB.GOLD.SKILL_STAGE TO ROLE reader_role;
GRANT READ ON STAGE HEALTHCARE_DB.GOLD.SKILL_STAGE TO ROLE reader_role;

-- Grant usage on the agent so reader_role can invoke it (and its skills)
GRANT USAGE ON AGENT HEALTHCARE_DB.GOLD.HEALTHCARE_AGENT TO ROLE reader_role;

GRANT USAGE ON SEMANTIC VIEW HEALTHCARE_DB.GOLD.HEALTHCARE_SEMANTIC_VW TO ROLE READER_ROLE;
GRANT SELECT ON SEMANTIC VIEW HEALTHCARE_DB.GOLD.HEALTHCARE_SEMANTIC_VW TO ROLE reader_role;